#! /bin/sh

sxhkd &

if xrandr -q | grep 'HDMI1 connected'; then
	xrandr --output HDMI1 --mode 1920x1080 --right-of eDP1
	bspc monitor eDP1 -d 1 3 5 7 9
	bspc monitor HDMI1 -d 2 4 6 8 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

compton -b -f &
nm-applet &
numlockx on
/home/bob/.config/polybar/launch.sh
xinput set-prop "DELL0767:00 06CB:7E92 Touchpad" "libinput Tapping Enabled" 1
/opt/Scripts/applets.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore

xset s off
xset -dpms

bspc rule -a Gnome-calculator state=floating
bspc rule -a KeePass2 desktop=^10
bspc rule -a Slack desktop=^9
